name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - .gitignore
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore twitter4j.properties for test
        run: echo ${{ secrets.TWITTER4J_PROPERTIES_BASE64 }} | base64 -d > twitter4j-v2-support/src/test/resources/twitter4j.properties

      - name: Unit Test
        run: ./gradlew test --info
